{% set name = "nexpy" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce2c75f865d57f2ceeb2c781a63021175f128d14bc6ff65b04a1dbfffa334344

build:
  number: 1
  entry_points:
    - nexpy = nexpy.nexpygui:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - ansi2html
    - darkdetect
    - dateparser
    - fabio
    - h5py
    - ipython
    - lmfit
    - matplotlib-base
    - mplcursors
    - nexusformat >=2.0.3
    - numpy
    - packaging
    - pillow
    - pygments
    - pylatexenc
    - python >={{ python_min }}
    - qtconsole-base
    - qtpy
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - nexpy
    - nexpy.gui
    - nexpy.models
    - nexpy.readers

about:
  home: http://nexpy.github.io/nexpy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'NeXpy: A Python GUI to analyze NeXus data'
  doc_url: https://nexpy.github.io/nexpy/
  dev_url: https://github.com/nexpy/nexpy

extra:
  recipe-maintainers:
    - rayosborn
    - willend
