{% set name = "nexpy" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 044c6c769a16baaff16b83ab26fea1cedd6895cd9b25d1f10924aba87220f9e5

build:
  number: 0
  entry_points:
    - nexpy = nexpy.nexpygui:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - ansi2html
    - fabio
    - h5py
    - ipython
    - lmfit
    - matplotlib
    - mplcursors
    - nexusformat >=2.0.0
    - numpy
    - packaging
    - pillow
    - pylatexenc
    - python >={{ python_min }}
    - qtconsole
    - qtpy
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - nexpy
    - nexpy.gui
    - nexpy.models
    - nexpy.readers
  commands:
    - nexpy --help

about:
  home: http://nexpy.github.io/nexpy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'NeXpy: A Python GUI to analyze NeXus data'
  doc_url: https://nexpy.github.io/nexpy/
  dev_url: https://github.com/nexpy/nexpy

extra:
  recipe-maintainers:
    - rayosborn
