{% set name = "nexpy" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/NeXpy-{{ version }}.tar.gz
  sha256: 3049bdcb26c2df8cb6ad5afa41ba044200a608f223b493d67e4c68d9a5c9e3e4

build:
  number: 0
  entry_points:
    - nexpy = nexpy.nexpygui:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - ansi2html
    - h5py >=2.9
    - ipykernel >=6.15.2
    - ipython
    - lmfit >=1.0.3
    - matplotlib-base
    - mplcursors
    - nexusformat >=1.0.2
    - numpy
    - pillow
    - pylatexenc
    - python >=3.7
    - qtconsole >=5.4.3
    - qtpy >=2.4
    - scipy
    - importlib-metadata

test:
  imports:
    - nexpy
    - nexpy.api
    - nexpy.api.frills
    - nexpy.api.frills.models
    - nexpy.gui
    - nexpy.plugins
    - nexpy.readers
  commands:
    - nexpy --help

about:
  home: http://nexpy.github.io/nexpy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'NeXpy: A Python GUI to analyze NeXus data'
  doc_url: https://nexpy.github.io/nexpy/
  dev_url: https://github.com/nexpy/nexpy

extra:
  recipe-maintainers:
    - rayosborn
