{% set name = "nexpy" %}
{% set version = "0.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/NeXpy-{{ version }}.tar.gz
  sha256: 6f8c05288488381f651833e49b1664c2d82bfc4a9387f679465cc0897ec4728a

build:
  number: 1
  entry_points:
    - nexpy = nexpy.nexpygui:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - numpy >=1.16.0
  run:
    - ansi2html
    - h5py
    - qtconsole
    - qtpy
    - ipython
    - matplotlib
    - nexusformat >=0.6.1
    - numpy >=1.16.0
    - lmfit >=1.0.2
    - pylatexenc
    - pillow
    - python >=3.6
    - scipy

test:
  imports:
    - nexpy
    - nexpy.api
    - nexpy.api.frills
    - nexpy.api.frills.functions
    - nexpy.definitions
    - nexpy.gui
    - nexpy.plugins
    - nexpy.readers
  commands:
    - nexpy --help

about:
  home: http://nexpy.github.io/nexpy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'NeXpy: A Python GUI to analyze NeXus data'
  doc_url: https://nexpy.github.io/nexpy/
  dev_url: https://github.com/nexpy/nexpy

extra:
  recipe-maintainers:
    - tschoonj
    - rayosborn
