{% set name = "nexpy" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/NeXpy-{{ version }}.tar.gz
  sha256: 3a25bc5610e61aa9df2aab1f2ea0c78a2360ee012798df8e0a12f6121a828c2b

build:
  number: 0
  entry_points:
    - nexpy = nexpy.nexpygui:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy
  run:
    - ansi2html
    - h5py
    - qtconsole
    - qtpy
    - ipython
    - matplotlib
    - nexusformat >=0.5.3
    - numpy
    - lmfit
    - pylatexenc
    - pillow
    - python
    - scipy

test:
  imports:
    - nexpy
    - nexpy.api
    - nexpy.api.frills
    - nexpy.api.frills.functions
    - nexpy.definitions
    - nexpy.gui
    - nexpy.plugins
    - nexpy.readers
  commands:
    - nexpy --help

about:
  home: http://nexpy.github.io/nexpy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'NeXpy: A Python GUI to analyze NeXus data'
  doc_url: https://nexpy.github.io/nexpy/
  dev_url: https://github.com/nexpy/nexpy

extra:
  recipe-maintainers:
    - tschoonj
    - rayosborn
