travis:
  secure:
    BINSTAR_TOKEN: OqyRLn+nWsyDgOlqlGGN7ok220alk5Ivjy4+o2pKca0vkZOYx9rLH6Hwi7Q2kvAj+MOco932PW6lNZ7u56quRIzeSn3f6RdRW5Bp7MRzWZgwH+vn1Ix2Oav00fqm90SckN0QsdOGJ6bH+7S8AMOZ1GW7yMCYZRqCjk74FjmZo9MxGvjVkR/Ro3ynshfGnzc3bF2FPSYh+Ji65bWwXQy4yHZtlkENjxT3R31GVVkbdicfeFVkR5eBHgZXVlydd08wmzcSMJBQ0yNmwU2VQwWUCEVuvH9Qr3svPKaWlNMEogRdnNKYzlEdThVh8LqML+rGvBzrc9bDNhv1cdbwU5rxzKn0UPTOvY8eawOpqUNwE3wwmG72RvnHuNVheK/s6EyuKzzGoPPbfU/H1GEPwSIGtbDzPuWJSOFHzhx4G96/X3mDjyA/jqFs0RXn6J7wwH7giPZ6EyB0ws2HsGhw0l1xILxwb6F/sxfqE3/CbUNzZ758D7iD6WR0Phjp2CnoUmgDdzupyspR4z99OLEJfSdptQpQM0TL87iTcTHRytp2D+q/DX8sYJmaIXeH7g6wfLv6tLb3VpS6CqcVOaZVtM1+u/MF0+/1exx3zyFU81Mdr2vm0v2BkXwYxE+hVEchM1fNg0R673ANqcgx9lJb5/tSBYG42/7duVOuewpo0XCySEo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
